### ISSUE TITLE
String representation of complex variables

### ISSUE THREAD

**Issue by manuel-guilbault** [Nuglif/nacl#3]
I can't find anywhere in the doc what should be the string representation of a complex variable (such as an object or an array) when encapsulated inside a string:

```
${var} = { k1 v1; k2 v2 }
my_var "enclosed ${var}"
```

What should be the value of `my_var` here? My guess is that `${var}` should be stringified as a JSON object (`{"k1":"v1","k2":"v2"}`), but I think it should be formally documented.

**Comment by adoy** [comment]
You're right, this is not documented. My first guess would be to trigger some kind of error. Not sure what would be a real use case of this kind of thing. Do you have one ?

@cdemers What do you think about this ?

**Comment by cdemers** [comment]
Interesting!  I guess as we are going for a tight and safe framing, I would go for an error, and maybe suggest a macro if one wished to display an object as a JSON string.

**Comment by cdemers** [comment]
Also, I had a guest who triggered errors once, I was happy when the evening was over.

**Comment by manuel-guilbault** [comment]
> Also, I had a guest who triggered errors once, I was happy when the evening was over.

Never let @adoy in your home!

**Comment by floverdevel** [comment]
What would be the value of `my_var` here?

```
${var} = "string"
my_var "enclosed ${var}"
```

**Comment by adoy** [comment]
@floverdevel In your case `enclosed string` as it is right now. 

There is no possible ambiguity here. That could also be true for int variables 
```
$var = 10;
my_var = "enclosed ${var"} // "enclosed 10"
```

For other types like float, objects, array I think we should trigger an error

1. I don't see any use case for this
2. There are many way this could be handle but none of them is intuitive.

**Comment by cdemers** [comment]
As there is no more activity, I will close this issue.  You are welcome to re-open it if there are any new development.
