### ISSUE TITLE
Le badge Latest Stable Version du README ne fonctionne pas

### ISSUE THREAD

**Issue by floverdevel** [Nuglif/nacl#5]
Le README affiche une image brisée sur la 6e ligne :
```
[![Latest Stable Version](https://poser.pugx.org/nuglif/nacl/v/stable)](https://packagist.org/packages/nuglif/nacl)
```

Un appel réseau à `view-source:https://poser.pugx.org/nuglif/nacl/v/stable`
donne une erreur 500 avec ce message :

> Predis\Connection\ConnectionException: Connection refused [tcp://localhost:6379] in /application/releases/20200519164607/vendor/predis/predis/src/Connection/AbstractConnection.php:155

**Comment by adoy** [comment]
Je pense que le site qui fournis les badges était juste temporairement down. Tout semble bien marcher en ce moment.

**Comment by floverdevel** [comment]
En effet ça semble correct à présent :+1:
